version: '3.8'

services:
  people-db:
    image: postgres:15
    container_name: people-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: people_db
    ports:
      - "7432:5432"
    networks:
      - people_network
    volumes:
      - people_db_data:/var/lib/postgresql/data


  people-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: people-api
    depends_on:
      - people-db
    ports:
      - "8080:8080"
    networks:
      - people_network
    command: ["./wait-for-it.sh", "people-db:5432", "--", "./people-api"]
    environment:
      - DATABASE_URL=postgres://postgres:postgres@people-db:5432/people_db?sslmode=disable

networks:
  people_network:
    driver: bridge

volumes:
  people_db_data: