basePath: /
definitions:
  domain.Person:
    properties:
      age:
        type: integer
      gender:
        type: string
      id:
        type: integer
      name:
        type: string
      nationality:
        type: string
      patronymic:
        type: string
      surname:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample People API.
  title: People API
  version: "1.0"
paths:
  /people:
    get:
      parameters:
      - description: Name
        in: query
        name: name
        type: string
      - description: Surname
        in: query
        name: surname
        type: string
      - description: Nationality
        in: query
        name: nationality
        type: string
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Person'
            type: array
      summary: List People
      tags:
      - People
    post:
      consumes:
      - application/json
      parameters:
      - description: Person Info
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/domain.Person'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
      summary: Create Person
      tags:
      - People
  /people/{id}:
    delete:
      parameters:
      - description: Person ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete Person
      tags:
      - People
    get:
      parameters:
      - description: Person ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Person'
      summary: Get Person by ID
      tags:
      - People
    put:
      consumes:
      - application/json
      parameters:
      - description: Person ID
        in: path
        name: id
        required: true
        type: integer
      - description: Person Info
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/domain.Person'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update Person
      tags:
      - People
swagger: "2.0"
